In [194]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

import warnings

warnings.filterwarnings('ignore')

In [1]:


data=datasets.load_iris()
x=data["data"]
y=data["target"]
#先做一个二分类问题
cond=y!=2
x=x[cond]
print(x.shape)
y=y[cond]
print(y)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)
lr=LogisticRegression(max_iter=1000,multi_class="ovr")
lr.fit(x_train,y_train)
w=lr.coef_
b=lr.intercept_
print(w)
p=lr.predict_proba(x_test)
print("=====================模型预测的概率：\n",p)

y_= x_test.dot(w[0].T)+b
proba_=1/(1+np.exp(-y_))
a=np.c_[1-proba_,proba_]
print("=====================计算得到的的概率：\n",a)


(100, 4)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[[ 0.46064286 -0.78751714  2.18664882  0.92839897]]
=====================模型预测的概率：
 [[0.04044534 0.95955466]
 [0.01045715 0.98954285]
 [0.98706156 0.01293844]
 [0.05442277 0.94557723]
 [0.13838323 0.86161677]
 [0.97966136 0.02033864]
 [0.98204789 0.01795211]
 [0.03292766 0.96707234]
 [0.03381355 0.96618645]
 [0.0085052  0.9914948 ]
 [0.02466546 0.97533454]
 [0.97515907 0.02484093]
 [0.00517643 0.99482357]
 [0.00238343 0.99761657]
 [0.00774374 0.99225626]
 [0.98618577 0.01381423]
 [0.96598134 0.03401866]
 [0.94905767 0.05094233]
 [0.00735426 0.99264574]
 [0.97742702 0.02257298]]
=====================计算得到的的概率：
 [[0.04044534 0.95955466]
 [0.01045715 0.98954285]
 [0.98706156 0.01293844]
 [0.05442277 0.94557723]
 [0.13838323 0.86161677]
 [0.97966136 0.02033864]
 [0.98204789 0.017952

In [4]:
# command + option + c 复制路径
path = '/Users/snszz/PycharmProjects/AVFL/RVFL_datasets/UCI/Balance_Scale/balance-scale.csv'
balance_scale = pd.read_csv(path, sep=',', encoding='utf-8', header=None)
balance_scale.head()

0  1  2  3  4
0  1  1  1  1  B
1  1  1  1  2  R
2  1  1  1  3  R
3  1  1  1  4  R
4  1  1  1  5  R

In [153]:
balance_scale_x = balance_scale.iloc[:,:-1].values
balance_scale_y = balance_scale.iloc[:, -1].values
x_train,x_test,y_train,y_test=train_test_split(balance_scale_x,balance_scale_y,test_size=0.2,random_state=1)
lr=LogisticRegression(penalty = 'none',max_iter=1000,multi_class="ovr")
lr.fit(x_train,y_train)
w=lr.coef_
b=lr.intercept_
print('w.shape \n', w.shape)
predict = lr.predict(x_test)
print("=====================模型预测的概率：\n",predict)
print(lr.score(x_test, y_test))

# 统计得分
score = sum(predict == y_test)
accuracy = score / y_test.shape[0]
print('accuracy:', accuracy)

w.shape 
 (3, 4)
=====================模型预测的概率：
 ['L' 'R' 'R' 'L' 'L' 'R' 'L' 'R' 'L' 'R' 'L' 'L' 'L' 'L' 'L' 'R' 'R' 'L'
 'L' 'R' 'L' 'L' 'L' 'L' 'L' 'R' 'L' 'R' 'R' 'R' 'L' 'L' 'R' 'L' 'R' 'L'
 'R' 'L' 'R' 'R' 'R' 'L' 'L' 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L'
 'L' 'R' 'L' 'L' 'R' 'R' 'L' 'R' 'R' 'L' 'L' 'R' 'L' 'R' 'L' 'L' 'L' 'R'
 'L' 'L' 'R' 'L' 'R' 'L' 'L' 'L' 'L' 'R' 'R' 'L' 'R' 'R' 'L' 'L' 'L' 'L'
 'L' 'L' 'L' 'R' 'L' 'L' 'R' 'L' 'L' 'L' 'L' 'L' 'R' 'R' 'L' 'L' 'R' 'R'
 'R' 'L' 'R' 'L' 'R' 'L' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'L' 'L' 'L' 'R']
0.832
accuracy: 0.832


In [18]:
lr.__dict__

{'penalty': 'none',
 'dual': False,
 'tol': 0.0001,
 'C': 1.0,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'class_weight': None,
 'random_state': None,
 'solver': 'lbfgs',
 'max_iter': 1000,
 'multi_class': 'ovr',
 'verbose': 0,
 'warm_start': False,
 'n_jobs': None,
 'l1_ratio': None,
 'n_features_in_': 4,
 'classes_': array(['B', 'L', 'R'], dtype=object),
 'n_iter_': array([18, 22, 20], dtype=int32),
 'coef_': array([[ 0.00505033, -0.10849751, -0.14430434,  0.00894745],
        [ 3.4253221 ,  3.53418944, -3.31746534, -3.37972654],
        [-3.7680909 , -3.72367707,  3.82426369,  3.75618513]]),
 'intercept_': array([-1.81740797, -1.60190567, -1.36577551])}

In [51]:
# lr.fit(lr.classes_)
print('classes: ', lr.classes_)
# # Return the mean accuracy on the given test data and labels.
print('train score: ', lr.score(x_train, y_train))
print('test score: ', lr.score(x_test, y_test))
print('all data score: ', lr.score(balance_scale_x, balance_scale_y))

d0 = balance_scale.loc[1]
d1 = balance_scale.loc[1, :3].values.reshape((-1, 4))
print(d0)
print(d1)

print('predict: ', lr.predict(d1))

print('predict_log_proba', lr.predict_log_proba(d1))   #Predict logarithm of probability estimates.

print('predict_proba', lr.predict_proba(d1))   # Probability estimates.

classes:  ['B' 'L' 'R']
train score:  0.888
test score:  0.832
all data score:  0.8768
0    1
1    1
2    1
3    2
4    R
Name: 1, dtype: object
[[1 1 1 2]]
predict:  ['R']
predict_log_proba [[-2.21348945 -4.77300934 -0.12530636]]
predict_proba [[0.10931852 0.0084549  0.88222658]]


In [31]:
(0.888*0.8 + 0.832 * 0.2) 

0.8768

In [52]:
lr.get_params()

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': None,
 'max_iter': 1000,
 'multi_class': 'ovr',
 'n_jobs': None,
 'penalty': 'none',
 'random_state': None,
 'solver': 'lbfgs',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [53]:
lr.densify()

LogisticRegression(max_iter=1000, multi_class='ovr', penalty='none')

In [55]:
lr.sparsify()

LogisticRegression(max_iter=1000, multi_class='ovr', penalty='none')

In [203]:
# 基于隐藏层对该函数使用回归
# 隐藏层的输入系数w, b是随机初始化为[-c, c]的均匀分布

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def softmax(x):
    x_exp = np.exp(x)
    #如果是列向量，则axis=0
    x_sum = np.sum(x_exp, axis = 0)
    s = x_exp / x_sum    
    return s
def SDs(predict, y_test):
    loss = np.sum((predict - y_test) ** 2, axis = 1)
    std = np.sqrt(sum(loss)) /  y_test.shape[0]
    return  std

def random_initialize_hidden(x, hiddennodes, c=1,seed=1111):
    '''
    inputnodes : 输入的特征数目
    hiddennodes: 隐藏层的节点数目
    n: 样本数量
    c ： 权重和bias的范围， 均匀分布
    '''
    np.random.seed(seed)
    n, inputnodes = x. shape
    hidden = np.zeros((n, hiddennodes))   # initial hidden layer
   
    w = np.random.uniform(-c, c, (inputnodes, hiddennodes))   # 生成weights
    b = np.random.uniform(-c, c, (hiddennodes))
    
    for i in range(n):
        hidden[i] = np.dot(w.T, x[i]) + b
     # 激活
    hidden = sigmoid(hidden)
    return hidden

def targets_encoder(targets, encoder = 'LabelEncoder'):
    label = targets.unique()
    print(label)
    dict_label = {}
    if encoder == 'LabelEncoder':
        # d对标签进行编码
        enc = LabelEncoder().fit(label)
        classes = enc.transform(label)    # enc.classes_
        targets = enc.transform(targets)
       
        for i in range(len(label)):
            dict_label[label[i]] = classes[i]

    elif encoder == 'OneHotEncoder':
        label1 = label[:,np.newaxis]   # [[],[]] 添加一个维度
        targets = targets[:, np.newaxis]
        enc = OneHotEncoder().fit(label1)
        classes= enc.transform(label1).toarray()
        targets = enc.transform(targets).toarray()        

    elif encoder == 'OrdinalEncoder':
        label1 = label[:,np.newaxis]   # [[],[]] 添加一个维度
        targets = targets[:, np.newaxis]
        enc = OrdinalEncoder().fit(label1)
        classes= enc.transform(label1)
        targets = enc.transform(targets)
        
    for i in range(len(label)):
        dict_label[label[i]] = classes[i]
    
    return targets, dict_label

In [79]:
balance_scale_x1 = balance_scale_x
balance_scale_y1 = balance_scale_y
balance_scale_x1_hidden = random_initialize_hidden(balance_scale_x1, hiddennodes=200, c=1,seed=1111 )
print('hidden shape', balance_scale_x1_hidden.shape)

x_train,x_test,y_train,y_test = train_test_split(balance_scale_x1_hidden, balance_scale_y1,test_size=0.2,random_state=1)

lr = LogisticRegression(penalty = 'none',max_iter=1000,multi_class="ovr")
lr.fit(x_train,y_train)
w = lr.coef_
b = lr.intercept_
print('w \n', w)
p=lr.predict(x_test)
print("=====================模型预测的概率：\n",p)

score = lr.score(x_test, y_test)    # Return the coefficient of determination  of the prediction.
print('score', score)

hidden shape (625, 200)
w 
 [[-1.97820445e-02 -6.21787497e-02 -7.44673288e-02 -9.24403307e-02
  -1.67063229e-01  1.11048321e-01 -6.14330164e-02  1.38035639e-02
  -5.64221131e-02  6.15489306e-02 -5.10316387e-02 -5.96534655e-02
   1.54727476e-01  3.58452261e-01  9.53278305e-02  1.07298617e-01
   6.28264362e-02  7.09282035e-02 -6.93086485e-02 -2.27413902e-02
   1.47362636e-02 -3.21341493e-02  1.08779601e-01 -6.65669904e-02
   2.05876056e-01 -1.67775573e-02 -1.91032358e-01 -6.98701135e-02
   4.10911341e-02 -1.16621902e-01  4.06676794e-02  1.84755393e-02
  -6.01272746e-02  7.36527212e-02  2.02156361e-02  8.84971016e-02
   1.23310620e-01  3.62368890e-01 -1.04238460e-02 -1.35027706e-02
   1.35287412e-02  1.55679201e-01  7.86825547e-03 -6.78063484e-02
  -1.90366994e-01  3.51520977e-02 -5.93934704e-02  7.35858816e-02
  -2.10669271e-02  3.06093461e-02  1.06541658e-02 -8.08276638e-02
   1.57326120e-02  7.79558919e-02  7.36692136e-03  8.32897000e-03
   1.27464706e-02 -2.30166133e-02  8.46653468e-0

/Users/snszz/opt/anaconda3/envs/tensorflow/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [144]:
balance_scale_x1 = balance_scale_x
balance_scale_y1 = balance_scale.iloc[:, 4]
balance_scale_x1_hidden = random_initialize_hidden(balance_scale_x1, hiddennodes=400, c=0.55,seed=1111 )
print('hidden shape', balance_scale_x1_hidden.shape)
balance_scale_y1, dict_label = targets_encoder(balance_scale_y1, encoder = 'OneHotEncoder')
x_train,x_test,y_train,y_test = train_test_split(balance_scale_x1_hidden, balance_scale_y1,test_size=0.1,random_state=1)

# 求 Moore–Penrose generalized inverse ：广义逆
x_train_inv = np.linalg.pinv(x_train)
# 回归系数
beta = np.dot(x_train_inv, y_train)
# 预测
predict = np.dot(x_test, beta)
# 提取标签
predict_label = np.argmax(softmax(predict), axis=1)

# 统计得分
score = []
for i in range(y_test.shape[0]):
    if predict_label[i] == np.argmax(y_test[i]):
        score.append(1)
    else:
        score.append(0)
accuracy = sum(score) / len(score)
print('accuracy:', accuracy)


hidden shape (625, 400)
['B' 'R' 'L']
accuracy: 0.5238095238095238


/Users/snszz/.local/lib/python3.7/site-packages/ipykernel_launcher.py:49: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.


In [137]:
lr = LinearRegression()
lr.fit(x_train, y_train)

w = lr.coef_
b = lr.intercept_
print('w.shape \n', w.shape)
predict=lr.predict(x_test)
print("=====================模型预测的概率：\n",predict[:5])

# 统计得分
score = []
for i in range(y_test.shape[0]):
    if predict_label[i] == np.argmax(y_test[i]):
        score.append(1)
    else:
        score.append(0)
accuracy = sum(score) / len(score)
print('accuracy:', accuracy)



w.shape 
 (3, 400)
=====================模型预测的概率：
 [[ 0.07738936  1.28355146 -0.36094082]
 [-0.2753665   0.9305991   0.3447674 ]
 [ 0.27129295 -0.27578741  1.00449446]
 [-0.16644666  0.58385495  0.58259171]
 [-0.6612903   1.5612959   0.09999441]]
accuracy: 0.06349206349206349


In [163]:
# 把所有数据的listdir一列换成输出类别

# {'diabetes.txt', 'transfusion.data', 'balance-scale.data'}
import os

path = r'/Users/snszz/PycharmProjects/AVFL/RVFL_datasets/UCI/'
data_path = []
for path1 in os.listdir(path):
    for path2 in os.listdir(path + path1):
        if path2.endswith('csv'): 
            path2 = path + path1  + '/' + path2
            data_path.append(path2)
len(data_path) 

15

In [138]:
# 使得其对于任意分类数据有用
# 1. 读入数据， path
# 2. 对特征和输出值分别进行处理， 特征---> 隐藏层权重初始化，拟合，激活； 输出-->one-hot编码, 
# 2.1 数据划分
# 3. Hb - T --->模型的求解
# 4. b = H^(-1) T,  H^(-1) ---定义成广义逆，
# 5. 预测 predict = H(x_test)b--->   使用softmax---->换算成概率
# 6. 求score：预测正确的个数
# 7. 求精度 accuracy = score / y_test.shape[0]
# 8. 标准差--- sum((predict - y_test) ** 2,axis = 1).sum() / y_test.shape[0]
# 9. 注意所得结果是30次试验的平均值

6.34

In [205]:
def main(path, max_iter = 30, hiddennodes=200, c=0.55,seed=np.random.randint(1e4)):
    # 1. 读入数据， path
    data = pd.read_csv(path, sep=',', header=None, encoding='utf-8')
    x = data.iloc[:, : -1].values
    y = data.iloc[:, -1]
    y, dict_label = targets_encoder(y, encoder='OneHotEncoder')
    accuracys = []
    standard_deviations = []
    for iter in range(max_iter):
        # 2. 对特征和输出值分别进行处理， 特征---> 隐藏层权重初始化，拟合，激活； 输出-->one-hot编码
        x = random_initialize_hidden(x, hiddennodes=hiddennodes, c=c, seed=seed)
        
        # 2.1 数据划分
        x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.2, random_state=1111)
    
        # 3. Hb - T --->模型的求解
        # 4. b = H^(-1) T,  H^(-1) ---定义成广义逆，
        # 5. 预测 predict = H(x_test)b---> 
        x_train_inv = np.linalg.pinv(x_train)
        # 回归系数
        b = np.dot(x_train_inv, y_train)
        # 预测
        predict = np.dot(x_test, b)
        # 提取标签
        predict_label = np.argmax(softmax(predict), axis=1)
    
        # 6. 统计得分
        score = []
        for i in range(y_test.shape[0]):
            if predict_label[i] == np.argmax(y_test[i]):
                score.append(1)
            else:
                score.append(0)
        # 7. 计算精度
        accuracy = sum(score) / len(score)
        
        # 计算标准差
        SD = SDs(predict, y_test)
        accuracys.append(accuracy)
        standard_deviations.append(SD)
    print('accuracy: \n', accuracys)
    print('standard deviations:\n',standard_deviations)
    # 计算平均accuracy,ave_SD
    ave_accuracy = sum(accuracys) / max_iter
    ave_SD = sum(standard_deviations) / max_iter
        
    
    return ave_accuracy, ave_SD
    
path = '/Users/snszz/PycharmProjects/AVFL/RVFL_datasets/UCI/Balance_Scale/balance-scale.csv'
ave_accuracy, ave_SD = main(path, hiddennodes=300, c=0.6, seed=np.random.randint(1e4))
ave_accuracy, ave_SD

['B' 'R' 'L']
accuracy: 
 [0.72, 0.672, 0.688, 0.704, 0.672, 0.712, 0.704, 0.728, 0.688, 0.72, 0.68, 0.688, 0.608, 0.696, 0.704, 0.696, 0.696, 0.688, 0.688, 0.704, 0.736, 0.744, 0.704, 0.688, 0.728, 0.664, 0.72, 0.664, 0.736, 0.672]
standard deviations:
 [0.09341743441677319, 0.07303751648101502, 0.06932033450553814, 0.06684055306197431, 0.0602198987163146, 0.06840504584842107, 0.06788866371115425, 0.06064102062511992, 0.07360747142013617, 0.06524882964766399, 0.07056586255105336, 0.07132721504844344, 0.07114385984877634, 0.05671871478191825, 0.0645747317235232, 0.06224136377115998, 0.06516405025138802, 0.06685178723669513, 0.07062427380753271, 0.06297100089869961, 0.06119980900938019, 0.06268725045593931, 0.06704606212328258, 0.06170205898124319, 0.06128266513746566, 0.06823257385996459, 0.060988888937811715, 0.0657826068706944, 0.058523864921134865, 0.06320305646131122]


(0.6970666666666668, 0.06638194883705094)